# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='lecture_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Lecture'),
        ),
        migrations.AddField(
            model_name='author',
            name='poster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Poster'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
