# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='lecture_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Lecture'),
        ),
        migrations.AlterField(
            model_name='author',
            name='poster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Poster'),
        ),
    ]
