# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20171123_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='titile',
            new_name='title',
        ),
    ]
