# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20171123_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='tags',
            field=models.ManyToManyField(to='activities.Tag'),
        ),
    ]
