# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='date',
            field=models.DateField(default='2010-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='vege',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
