# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0003_auto_20171112_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='ConfDay',
        ),
    ]
