# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodation', '0004_auto_20171113_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='date',
            field=models.DateField(default='10/10/10'),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='remark',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='vege',
            field=models.BooleanField(default=False),
        ),
    ]
