# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0007_auto_20171130_2152'),
        ('poll', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Poster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
