# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0007_auto_20171130_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoosedLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Lecture')),
            ],
        ),
    ]
